# Generated by Django 6.0.5 on 2026-07-07 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteCartera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=30, unique=True)),
                ('cliente', models.CharField(max_length=250)),
                ('direccion', models.CharField(blank=True, max_length=250)),
                ('ciudad', models.CharField(blank=True, max_length=120)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('celular', models.CharField(blank=True, max_length=50)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('asesor', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='FacturaCartera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factura', models.CharField(max_length=50)),
                ('fecha_expedicion', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('dias_mora', models.IntegerField(default=0)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='cartera.clientecartera')),
            ],
            options={
                'ordering': ['-dias_mora'],
            },
        ),
    ]
