# Generated by Django 6.0.5 on 2026-07-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facturacartera',
            options={},
        ),
        migrations.RemoveField(
            model_name='clientecartera',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='facturacartera',
            name='dias_mora',
        ),
        migrations.AddField(
            model_name='clientecartera',
            name='barrio',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='clientecartera',
            name='cantidad_facturas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clientecartera',
            name='cobrador',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='clientecartera',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='clientecartera',
            name='saldo_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='clientecartera',
            name='zona',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='facturacartera',
            name='detalle',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='facturacartera',
            name='estado',
            field=models.CharField(default='VENCIDA', max_length=30),
        ),
        migrations.AddField(
            model_name='facturacartera',
            name='forma_pago',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='facturacartera',
            name='tipo',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='facturacartera',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='clientecartera',
            name='ciudad',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
