# Generated by Django 6.0.5 on 2026-07-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0002_alter_facturacartera_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacionCartera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('clientes', models.IntegerField(default=0)),
                ('facturas', models.IntegerField(default=0)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
            ],
        ),
    ]
