# Generated by Django 6.0.5 on 2026-05-22 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_asesor'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='asesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.asesor'),
        ),
    ]
