# Generated by Django 6.0.5 on 2026-05-22 17:04

import clientes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_asesor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asesor',
            name='codigo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(upload_to=clientes.models.ruta_documentos),
        ),
    ]
