# Generated by Django 6.0.5 on 2026-05-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_asesor_codigo_alter_documento_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asesor',
            name='codigo',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
