# Generated by Django 6.0.5 on 2026-05-22 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_asesor_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.CharField(choices=[('vinculacion', 'Formato Vinculación'), ('rut', 'RUT'), ('camara', 'Cámara Comercio'), ('cedula', 'Cedula'), ('otro', 'Otro')], max_length=50),
        ),
    ]
