# Generated by Django 6.0.5 on 2026-05-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_auditoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='documento',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
